name: email-sync

on:
  workflow_dispatch:

jobs:
  email-sync:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Pull a Docker image
    - name: Pull Docker Image
      run: docker pull gilleslamiral/imapsync:2.295

    # Step 2: Run the Docker container
    - name: Run Docker Container
      run: docker run --rm gilleslamiral/imapsync:2.295 imapsync --host1 "${{ secrets.SOURCE_HOST_1 }}" --user1 "${{ secrets.SOURCE_USER_1 }}" --password1 "${{ secrets.SOURCE_PW_1 }}" --host2 "${{ secrets.TARGET_HOST_1 }}" --user2 "${{ secrets.TARGET_USER_1 }}" --password2 "${{ secrets.TARGET_PW_1 }}" --folder "INBOX" --folder "Sent" --folder "Drafts"
